### PR TITLE
Add to series: “Christopher Robin”

### PR DESCRIPTION
**Pull request by bentley**
*Winnie the Pooh* should be part of a series with Milne’s other works *When We Were Very Young*, *Now We Are Six*, and *The House on Pooh Corner*. All four books feature Pooh Bear and Christopher Robin, and they are often sold as a box set ([example](https://www.barnesandnoble.com/w/pooh-library-original-4-volume-set-a-a-milne/1106464910?ean=9780525444510)) or an omnibus ([example](https://www.barnesandnoble.com/w/the-complete-tales-and-poems-of-winnie-the-pooh-a-a-milne/1029724170?ean=9780525467267)).

In my opinion, the series should not be named after Pooh himself, although he appears in all four books, because he is not consistently named “Winnie the Pooh”: as *Winnie the Pooh*’s [introduction](https://standardebooks.org/ebooks/a-a-milne/winnie-the-pooh/text/introduction) relates, he was named Edward Bear in *When We Were Very Young*, and in that book the name “Pooh” refers instead to a swan. Edward Bear is also only a minor character in the first book, appearing in just one poem.

Christopher Robin is a better namesake for the series, because he’s a major, named character in all four books, the primary subject of the first and third, and nearly as well‐known a name as Winnie the Pooh.

Box sets usually put *Winnie the Pooh* first, presumably for marketing reasons. I think we should instead order them by publication date, especially because two of the titles relate to Christopher Robin’s age. Thus:

1. *When We Were Very Young*
2. *Winnie the Pooh*
3. *Now We Are Six*
4. *The House on Pooh Corner*

### CODE REVIEW

**Comment by acabal** [comment]
I see what you're getting at but naming it after Christopher Robin is not obvious. Even the box sets you link to call it the Winnie the Pooh series, and that's how it's universally recognized even in the first book where that's not yet his name. I think we should go with the more obvious choice here and call it the `Winnie-the-Pooh` set.

**Comment by bentley** [comment]
Revised to name the collection “Winnie the Pooh” instead of “Christopher Robin.”

Used spaces instead of hyphens because we also use spaces in the book title. Or did you want the hyphens?

**Comment by acabal** [comment]
Let's use dashes. After looking at the print copies they all have dashes so we need to update the actual book title to match. I'll do that later.

**Comment by bentley** [comment]
Updated to use hyphens.

I also hyphenated references to the character “Winnie the Pooh” in the description. Since you said you’d change the book title I’ll leave that to you though.

**Comment by acabal** [comment]
Excellent, thanks!

**Pull request merged**
